<?php return array (
  'site_title' => 'MineSwap',
  'base_color' => '#f33939',
  'time_zone' => 'America/Panama',
  'currency' => 'USD',
  'currency_symbol' => '$',
  'theme' => 'royalblue',
  'fraction_number' => 2,
  'paginate' => 10,
  'email_verification' => 1,
  'email_notification' => 1,
  'sms_verification' => 0,
  'sms_notification' => 0,
  'sender_email' => 'edgar.ng03@gmail.com',
  'sender_email_name' => 'MineSwap',
  'email_configuration' => 
  array (
    'name' => 'smtp',
    'smtp_host' => 'gmail.com',
    'smtp_port' => '465',
    'smtp_encryption' => 'ssl',
    'smtp_username' => 'edgar.ng03@gmail.com',
    'smtp_password' => 'Magoo26@@',
  ),
  'push_notification' => 1,
  'plan_sale_commission' => 1,
  'deposit_commission' => 1,
  'strong_password' => 0,
  'registration' => 1,
  'address_verification' => 0,
  'identity_verification' => 0,
  'error_log' => 1,
  'joining_bonus' => 0,
  'bonus_amount' => 10,
  'maintenance' => 0,
  'maintenance_message' => 'Sorry for the inconvenience.<br />Our website is currently undergoing scheduled maintenance.',
  'is_active_cron_notification' => 0,
);