<?php

$arr = [
    "Home",
    "About Us",
    "Blog",
    "FAQ",
    "Useful Links",
    "Other Links",
    "Language",
    "All Rights Reserved",
    "Mark all ase read",
    "unread messages",
    "No notifications",
    "Select Coin",
    "Select Plan",
    "Estimated Revenue",
    "Subscribe",
    "Your Card Information",
    "Enter your card number",
    "Enter the name on your card",
    "PLEASE SEND EXACTLY",
    "TO",
    "SCAN TO SEND",
    "Please follow the instruction below",
    "You have requested to deposit",
    "for successful payment",
    "Please pay",
    "Confirm Now",
    "Pay via Monnify",
    "Pay with VoguePay",
    "More",
    "Admin Feedback",
    "No response from Admin",
    "Wallet",
    "Please update your wallet address",
    "Min. Limit",
    "Max. Limit",
    "Payout Now",
    "Upgrade Wallet Address",
    "Enter Amount",
    "Transaction Preview",
    "Payment Status",
    "Upload",
    "Welcome",
    "Profile Information",
    "Password Setting",
    "Identity Verification",
    "Address Verification",
    "Preferred language",
    "Select Language",
    "Update Information",
    "Update Password",
    "Identity Type",
    "Select Type",
    "Select",
    "You previous request has been rejected",
    "Select Image",
    "Change",
    "Remove",
    "Your KYC submission has been pending",
    "Your KYC already verified",
    "Enter Subject",
    "Message",
    "Enter Message",
    "Create Ticket",
    "Replied",
    "Last Reply",
    "Action",
    "Open",
    "Answered",
    "Customer Reply",
    "Closed",
    "Image Upload",
    "Upload File",
    "Reply",
    "File",
    "Confirmation",
    "Are you want to close ticket",
    "Confirm",
    "Payment Log",
    "Type Here",
    "All Payment",
    "Complete Payment",
    "Pending Payment",
    "Cancel Payment",
    "Gateway",
    "Status",
    "Pending",
    "Cancel",
    "Search for Transaction ID",
    "Remark",
    "Transaction ID",
    "PLAN",
    "PRICE",
    "PROFIT",
    "TOTAL DAYS",
    "REMAIN DAYS",
    "STATUS",
    "Active",
    "Complete",
    "MORE",
    "REF",
    "Miner",
    "Profit",
    "Total Days",
    "Remain Days",
    "Purchased At",
    "Details",
    "Search User",
    "Search",
    "SL No",
    "Bonus From",
    "Remarks",
    "Time",
    "No Data Found",
    "Disable 2FA",
    "Two Factor Authenticator",
    "Enable 2FA",
    "Google Authenticator",
    "Use Google Authenticator to Scan the QR code  or use the code",
    "Google Authenticator is a multifactor app for mobile devices. It generates timed codes used during the 2-step verification process. To use Google Authenticator, install the Google Authenticator application on your mobile device",
    "DOWNLOAD APP",
    "Verify Your OTP",
    "VerifyVerify Your OTP to Disable",
    "Enter Google Authenticator Code",
    "Verify",
    "Email Verification",
    "Dashboard",
    "Referral Member",
    "Bonus Earned",
    "Referral link",
    "Automatically top up your account balance by sharing your referral link, Earn a percentage of whatever plan your referred user buys",
    "Plan Name",
    "Next",
    "Transaction Limit",
    "Payment By",
    "Amount",
    "Payable",
    "Conversion Rate",
    "Referral Bonus",
    "Referral Link",
    "Level",
    "Email",
    "Joined At",
    "Wallet Address",
    "Balance",
    "Enter your",
    "Update Wallet",
    "No Wallet Found",
    "Posted By Admin",
    "Recent Post",
    "Address",
    "Phone Number",
    "Subject",
    "Send Message",
    "Price",
    "Duration",
    "For",
    "Referral",
    "Hashrate",
    "Buy Now",
    "Plan Price",
    "Payment Type",
    "Select One",
    "Pay Via Online",
    "Pay Via Fund",
    "Pay Now",
    "403 Forbidden",
    "opps",
    "You don’t have permission to access ‘/’ on this server",
    "404",
    "Sorry page was not found",
    "We're sorry, the page you requested could not be found. Please go back to the homepage or contact us at",
    "Method not allowed",
    "Session has expired",
    "Internal Server Error",
    "The server encountered an internal error misconfiguration and was unable to complate your request. Please contact the server administrator",
    "Back To Home",
    "Please confirm your password before continuing",
    "Forgot Your Password",
    "Reset Your Account",
    "Please Insert your email address to retrieve your account",
    "Enter your Email Address",
    "Send Password Reset Link",
    "Reset Password",
    "New Password",
    "Change Password",
    "Code",
    "Submit",
    "Resend code",
    "Login",
    "Sign In Your Account",
    "Please Insert your login credentials to access your data",
    "Email Or Username",
    "Remember me",
    "Forgot Password",
    "Sign In",
    "Don't have an account yet",
    "Create Account",
    "Create Your Account",
    "Sponsor By",
    "First Name",
    "Last Name",
    "Username",
    "Email Address",
    "Your Phone Number",
    "Password",
    "Confirm Password",
    "Accepting all the terms & conditions",
    "Sign Up",
    "Already have an account",
    "Login Now",
    "Email Verify",
    "Verify Your Email Address",
    "A fresh verification link has been sent to your email address",
    "Before proceeding, please check your email for a verification link.",
    "If you did not receive the email",
    "click here to request another",
    "Name",
    "Please fill in the payment method name",
    "Currency",
    "Please fill in the currency",
    "Currency Symbol",
    "Please fill in the currency symbol",
    "Convention Rate",
    "Please fill in the convention rate",
    "Minimum Deposit Amount",
    "Please fill in the minimum deposit amount",
    "Maximum Deposit Amount",
    "Please fill in the maximum deposit amount",
    "Percentage Charge",
    "Please fill in the percentage charge",
    "Fixed Charge",
    "Please fill in the fixed charge",
    "Please fill in the",
    "User Contact Number",
    "Receiver Message",
];

return $arr;
